import type { Metadata } from "next";
import "./globals.css";
import Header from "@portfolio/components/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="w-5/6 h-[100vh] sm:w-[100%] md:px-32 md:h-[100vh] sm:px-[32px] overflow-x-hidden">
        <Header />
        {children}
        
      </body>
    </html>
  );
}
